places = {'house1':['money', 'material', 'material', 'melee', 'clothing', 'food'],  
'corner store':['material', 'money', 'melee', 'food', 'material', 'clothing'],   
'hospital': ['medkit'  , 'vehicle'  , 'medkit'  , 'material'  , 'clothing'  , 'material'],  
'police station': ['ammo'  , 'gun'  , 'vehicle'  , 'melee'  , 'food'  , 'ammo'],   
'house2': ['clothing'  , 'money'  , 'food'  , 'money'  , 'food'  ,'material'],   
'hunting shack':['gun'  , 'food'  , 'ammo'  , 'melee'],   
'army base': ['gun'  , 'ammo'  , 'melee'  , 'vehicle'  , 'ammo'  , 'melee'  , 'gun'  , 'vehicle'],  
'house3': ['vehicle'  , 'clothing'  , 'gun'  , 'material'  , 'money' , 'medkit'],   
'parking lot': ['vehicle'  , 'gun'  , 'material'  , 'vehicle'  , 'melee'  , 'vehicle'],   
'grocery store': ['food'  , 'material'  , 'money'  , 'food'  , 'food'  , 'material'],   
'gas station': ['gas'  , 'food'  , 'gas'  , 'material'  , 'money'  , 'melee'],   
'house4': ['clothing'  , 'ammo'  , 'food'  , 'clothing'  , 'food'  , 'material'],   
'parking lot2': ['med kit'  , 'vehicle'  , 'ammo'  , 'food'  , 'money'  , 'vehicle'],   
'corner store2': ['food'  , 'clothing', 'material'  , 'material', 'money'  ,'clothing'  ,'food' ,'gun'],
'hunting shack2':['money',   'gun'  , 'ammo'  , 'melee'  , 'ammo'  , 'material'],   
'bank': ['money'  , 'money'  , 'vehicle'  , 'money'  , 'medkit'  , 'money'],   
'gas station3': ['gas'  , 'money'  , 'gas'  , 'gas'  , 'material'  , 'food'],   
'grocery store2': ['food'   , 'money'  , 'food'  , 'food'  , 'material'  , 'money'],   
'clothing bank': ['clothing'  , 'material'  ,'clothing'   ,'clothing'   ,'material'   ,'money'],  
'gas station2': ['gun'  , 'gas'  , 'gas'  , 'gas'  , 'ammo'  , 'material']}  

